<div>

  <div class="row">
    <div class="small-text-center medium-6 columns medium-text-left">
      <dnn:PRIVACY ID="dnnPrivacy" runat="server" CssClass="footerLink" />
      <asp:Label ID="Label1" runat="server" Text="&nbsp;|&nbsp;" CssClass="footerLink"></asp:Label>
      <dnn:COPYRIGHT ID="dnnCopyright" runat="server" CssClass="footerLink" />
    </div>
                <div id="login-holder" class="text-right">                      
    <div id="login" class="small-text-center medium-6 columns medium-text-right">
      <dnn:LOGIN ID="dnnLogin" runat="server" CssClass="LoginLink" LegacyMode="true" />
      <dnn:USER ID="dnnUser" runat="server" CssClass="LoginLink" LegacyMode="true" />  
      <!-- br / -->

    </div>
    </div>
  </div>
  
</div>
